"""Data contracts for the email ingestion pipeline.

All pipeline modules pass data using these dataclasses.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(frozen=True)
class Email:
    """Raw email fetched from Microsoft Graph."""

    id: str
    subject: str
    sender: str
    timestamp: datetime
    body_text: str
    body_html: str
    links: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class ArticleContent:
    """Article text fetched from a link found in an email."""

    url: str
    title: str  # From <title> or <h1>
    text: str  # Clean article text, max 500 chars
    email_index: int  # Which input email this came from


@dataclass(frozen=True)
class DigestReport:
    """Aggregated intelligence brief generated by the LLM."""

    strategic_intel: str
    engineering: str
    tools_and_ops: str
    radar: str
    source_indices: list[int] = field(default_factory=list)


@dataclass(frozen=True)
class DigestOutput:
    """Final digest ready for sending."""

    generated_at: datetime
    total_processed: int
    report: DigestReport
    source_emails: list[Email] = field(default_factory=list)
    html: str = ""
