"""Data contracts for the email ingestion pipeline.

All pipeline modules pass data using these dataclasses.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(frozen=True)
class Email:
    """Raw email fetched from Microsoft Graph."""

    id: str
    subject: str
    sender: str
    timestamp: datetime
    body_text: str
    body_html: str
    links: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class DigestReport:
    """Aggregated intelligence brief generated by the LLM."""

    breaking_news: str
    tech_stacks: str
    new_software: str
    deep_dives: str
    source_indices: list[int] = field(default_factory=list)


@dataclass(frozen=True)
class DigestOutput:
    """Final digest ready for sending."""

    generated_at: datetime
    total_processed: int
    report: DigestReport
    source_emails: list[Email] = field(default_factory=list)
    html: str = ""
